FROM mcr.microsoft.com/dotnet/sdk:8.0 AS publish
WORKDIR /src
COPY ["ApiGateway/pizza_shop.gateway/pizza_shop.gateway.csproj", "./gateway"]
RUN dotnet restore "src/gateway/pizza_shop.gateway.csproj"
copy . .
RUN dotnet publish "src/gateway/pizza_shop.gateway.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "pizza_shop.gateway.dll"]